Repository opensearch-project/asynchronous-search, pull requests merged in 2021-12, with the labels that each got.

#82 Backports 1.3 version bump to 1.x
  .github/workflows/build.yml
  .github/workflows/multi-node-test-workflow.yml
  build.gradle
Labels: backport 1.x

#79 Bumping async search to 1.2.2.0
  .github/workflows/build.yml
  .github/workflows/multi-node-test-workflow.yml
  build.gradle
Labels: v1.2.2

#84 Incremented version to 1.2.3.
  .github/workflows/build.yml
  .github/workflows/multi-node-test-workflow.yml
  build.gradle
Labels: v1.2.3
